apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-database
  namespace: staging
spec:
  selector:
    matchLabels:
      app: auth-database
  replicas: 1
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auth-database
    spec:
      containers:
        - name: auth-database
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017

          volumeMounts:
            - name: auth-database-persistent-storage
              mountPath: "/data/db"

      volumes:
        - name: auth-database-persistent-storage
          emptyDir: { }

# service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-database
  namespace: staging
  labels:
    app: auth-database
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 27017
  type: NodePort
  selector:
    app: auth-database






