apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: gervasioartur/wallet-wise_auth-service:<IMAGE_TAG>
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb+srv://gervasioarthur:0199@auth-database.muyf4pw.mongodb.net/?retryWrites=true&w=majority&appName=auth-database
            
  selector:
    matchLabels:
      app: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: staging
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: auth-service