apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: <NAMESPACE>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: gervasioartur/wallet-wise_auth-service:<IMAGE_TAG>
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef: 
                name: <CONFIG_MAP>

  selector:
    matchLabels:
      app: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: <NAMESPACE>
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: auth-service